config/routes.rb
Rails.application.routes.draw do

  root to: 'events#index'
  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users
  resources :events do
   resources :attendances
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :participant, class_name: 'User'
  belongs_to :event

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :admin, class_name: 'User'
  has_many :attendances
  has_many :participants, class_name: 'User', through: :attendances

  #validates :start_date, presence: true, start_date: true
  validates :duration, presence: true
  validates :title, presence: true, length: { in: 5..140 }
  validates :description, presence: true, length: { in: 20..1000 }
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 1000 }
  validates :location, presence: true

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 has_many :events, foreign_key: 'admin_id', class_name: 'Event'
 has_many :attendances, foreign_key: 'participant_id', class_name: 'Attendance'
 
 after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def show
    @event = Event.find(params[:id])
  end

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    event_params = params.require(:event).permit(
      :start_date,
      :duration,
      :title,
      :description,
      :price,
      :location
    )
    @event = Event.new(event_params)
    @event.admin = current_user
    if @event.save
      flash[:success] = "L'événement a bien été créé !"
      redirect_to event_path(@event.id)
    else
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
def index
    @users = User.all
end
  def show
    unless is_good_user?(params[:id])
      redirect_to user_path(current_user.id)
    end
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    puts params
    @user = current_user
    user_params = params.require(:user).permit(:first_name, :last_name, :description)
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def is_good_user?(id)
    current_user == User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
  
      <h1 class= 'header-title'><font  color="#668FFF">Tongasoa sur EventGasy 😋</font></h1>
    </div>
    <div class="container-fluid">
      <div class="row d-flex align-items-stretch">
        <% @events.each do |event| %>
          <div class="col-sm-6 col-md-4 py-4">
            <div class="card w-100 mb-4 box-shadow h-100 rounded-lg">
              <div class="card-body">
                <h5 class="card-title">
                  <%= link_to event.title, event_path(event.id) %>
                </h5>
                <p class="card-subtitle text-muted"><%= event.start_date %></p>
                <p class="card-subtitle text-muted"><%= event.location %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/events/new.html.erb
<div class="container" >
     <div class="row">
         <div class="col-md-8 mx-auto mt-5">
         <%= form_tag url_for(action: "create"), method: "post" do |f| %>
       <%= label_tag 'Start_Date' %>
       <%= text_field_tag 'start_date', @event.start_date, class: 'form-control'%>
       <%= label_tag 'Duration' %>
       <%= text_field_tag 'duration', @event.duration, class: 'form-control'%>
       <%= label_tag 'Location' %>
       <%= text_field_tag 'location', @event.location, class: 'form-control'%>
       <%= label_tag 'Title' %>
       <%= text_field_tag 'title', @event.title, class: 'form-control'%>
       <%= label_tag 'Description' %>
       <%= text_field_tag 'description', @event.description, class: 'form-control'%>
       <%= label_tag 'Price' %>
       <%= text_field_tag 'price', @event.price, class: 'form-control'%>
       <br/>
       <%= submit_tag "Modify event", class: 'btn btn-lg btn-primary btn-block' %>
     <% end %>
         </div>
     </div>
 </div>

app/views/events/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col text-center">
      <h1><%= @event.title %></h1>
    </div>
  </div>

  <div class="card mb-3 border-primary border-left-0">
    <div class="row">
      <div class="col">
        <div class="card-body">
          <p class="card-text"><strong>Description : </strong><%= @event.description %></p>
          <p class="card-text"><strong>Nombre de Participants : </strong><%= @event.attendances.count %></p>
          <p class="card-text"><strong>Date de début : </strong><%= @event.start_date %></p>
          <p class="card-text"><strong>Prix : </strong><%= @event.price %> €</p>
          <p class="card-text"><strong>Lieu de l'événement : </strong><%= @event.location %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventGasy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  

    <!-- Bootswatch CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/superhero/bootstrap.min.css" rel="stylesheet" integrity="sha384-LS4/wo5Z/8SLpOLHs0IbuPAGOWTx30XSoZJ8o7WKH0UJhRpjXXTpODOjfVnNjeHu" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <%= link_to "EventGasy", root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        </ul>
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Créer un événement", new_event_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Voir Profil", user_path(current_user.id), class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Se déconnecter", destroy_user_session_path, class: 'nav-link', :method => :delete %>
          </li>
          <% else %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Connexion
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "S'inscrire", new_user_registration_path, class: 'dropdown-item' %>
              <div class="dropdown-divider"></div>
              <%= link_to "Se Connecter", new_user_session_path, class: 'dropdown-item' %>
            </div>
          </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container" >
     <div class="row">
         <div class="col-md-8 mx-auto mt-5">
         <%= form_tag url_for(action: "update"), method: "put" do |f| %>
       <%= label_tag 'First name' %>
       <%= text_field_tag 'first_name', current_user.first_name, class: 'form-control'%>
       <%= label_tag 'Last name' %>
       <%= text_field_tag 'last_name', current_user.last_name, class: 'form-control'%>
       <%= label_tag 'Description' %>
       <%= text_field_tag 'description', current_user.last_name, class: 'form-control'%>
       <%= label_tag 'email' %>
       <%= text_field_tag 'email', current_user.email, class: 'form-control'%>
       <br/>
       <%= submit_tag "Modify profil", class: 'btn btn-lg btn-primary btn-block' %>
     <% end %>
         </div>
     </div>
 </div>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="container mt-4">
      <h1 class='text-center'>Ton profil</h1>
      <br />
      <div class="card mb-3 border-primary border-left-0">
        <div class="row no-gutters">
          <div class="col-2 col-lg-1 m-auto text-center">
            <img src="/images/user.png" alt="">
          </div>
          <div class="col-10 col-lg-11">
            <div class="card-body">
              <p class="card-text"><strong>Prénom : </strong><%= @user.first_name %></p>
              <p class="card-text"><strong>Nom : </strong><%= @user.last_name %></p>
              <p class="card-text"><strong>Description : </strong><%= @user.description %></p>
              <p class="card-text"><strong>Email : </strong><%= @user.email %></p>
            </div>
          </div>
        </div>
        <div class="row no-gutters">
          <div class="col-10 offset-2 col-lg-11 offset-lg-1">
            <div class="card-body">
              <p>
                <%= link_to "Modifier mes identifiants", edit_user_registration_path, class: 'btn btn-primary' %>
                <%= link_to "Modifier mes informations", edit_user_path(@user.id), class: 'btn btn-primary' %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row d-flex align-items-stretch">
        <% @user.events.each do |event| %>
          <div class="col-sm-6 col-md-4 py-4">
            <div class="card w-100 mb-4 box-shadow h-100 rounded-lg">
              <div class="card-body">
                <h5 class="card-title">
                  <%= link_to event.title, event_path(event.id) %>
                </h5>
                <p class="card-subtitle text-muted"><%= event.start_date %></p>
                <p class="card-subtitle text-muted"><%= event.location %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </body>
</html>